"""
Django settings for biocommerce project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b%a7m!qt!ij1hkxcqq95ld!^v+9%8!w5!19if^2!lvo)=$h6g#'
STRIPE_PUBLISHABLE_KEY = "pk_live_51RVuzZE7HVY39HFDVd9jGQoYWWMQbtH3QMicvwCNdp16C8uN07Bt2rVsvvk8aBcIbSnhT3AvxAEDgEQ4JlcUnMY800f3jzgGP9"
STRIPE_SECRET_KEY = "sk_test_51RVuzfCjeYG66sme6KHmhIJCiHiBNhmfpbaDfkn3NHdwkm6QyhMPStySVwwvuhGeyiV4NKyxhXSciTEURbdTpE007wLFnZvO"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['18.188.141.97','joshuamarin.me', 'www.joshuamarin.me', '*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_browser_reload",
    'products',
    'cart',
    'orders',
    'dj_database_url',
    'corsheaders',
    'api',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.middleware.gzip.GZipMiddleware'
]

ROOT_URLCONF = 'biocommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biocommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = "postgresql://postgres.kcarooudfegtfwqhnwyw:S1steemas25@aws-1-us-east-2.pooler.supabase.com:5432/postgres"

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)
}

DATABASES['default'].update({
    'CONN_MAX_AGE': 0,   # cierra la conexión al final de cada request
    'OPTIONS': {'sslmode': 'require'},  # si Supabase requiere SSL
})

# Password validation
# https://docs.djangoproject.coen/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / STATIC_URL]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'mediafiles'
# Asumiendo que tienes una URL llamada 'profile'
LOGIN_REDIRECT_URL = 'products:landing_page'
LOGOUT_REDIRECT_URL = 'login'  # Redirige de nuevo a la página de login
ALLOWED_HOSTS = ['*']  # Permite todas las solicitudes de host


CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # recommended
        # 'rest_framework.authentication.SessionAuthentication',  # optional
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # tighten in prod
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Email configuration
# For development you can use the console backend which prints emails to the runserver console:
#   EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production use SMTP (example using Gmail / SMTP relay). Set these values in environment variables
# and keep credentials out of source control.
DEFAULT_FROM_EMAIL = 'no-reply@example.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'stormblessedtrujo@gmail.com'  # set via env var
EMAIL_HOST_PASSWORD = 'ewqu dpuq hfpg rlfv '  # set via env var

# Example (PowerShell) to set env vars for local development before running Django:
# $env:EMAIL_HOST_USER = 'your-smtp-user'
# $env:EMAIL_HOST_PASSWORD = 'your-smtp-password'

# If you prefer testing without sending real emails, uncomment the console backend:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
