# Generated by Django 5.2.1 on 2025-09-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_producto_id_producto_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.PositiveIntegerField(default=1)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.producto')),
                ('CART', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart_model')),
            ],
        ),
    ]
