# Generated by Django 5.2.1 on 2025-09-02 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
        ('products', '0002_remove_producto_id_producto_id_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('ADDRESS', models.CharField(max_length=150)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('PAID', models.BooleanField(default=False)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QUANTITY', models.PositiveIntegerField(default=1)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.producto')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order_model')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
