# Generated by Django 5.2.1 on 2025-05-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NOMBRE', models.CharField(max_length=50)),
                ('CAT_SLUG', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROD_NOMBRE', models.CharField(max_length=50)),
                ('PROD_DESCRIPCION', models.CharField(blank=True, max_length=50)),
                ('PROD_SLUG', models.SlugField(max_length=250)),
                ('CONTENIDO_PZS', models.CharField(blank=True, max_length=50)),
                ('PROD_PRECIO_MAY', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PROD_PRECIO_PUB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PROD_DISPONIBLE', models.BooleanField(default=True)),
                ('PROD_GRAMAJE', models.FloatField(blank=True, null=True)),
                ('PROD_IMAGEN', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('PROD_CREADO', models.DateTimeField(auto_now_add=True)),
                ('PROD_MODIFICADO', models.DateTimeField(auto_now=True)),
                ('PROD_CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.categoria')),
            ],
        ),
    ]
