# Generated by Django 5.2.1 on 2025-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_producto_id_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PROD_DESCRIPCION_DESC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='STOCK_PROD',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PROD_NOMBRE',
            field=models.CharField(max_length=150),
        ),
    ]
