# Generated by Django 5.2.1 on 2025-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_producto_id_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PROD_NOMBRE',
            field=models.CharField(max_length=150),
        ),
    ]
